executor: KubernetesExecutor

# db config
postgresql:
  enabled: true
  postgresqlUsername: airflow
  postgresqlPassword: airflow
  postgresqlDatabase: airflow

# Airflow web
web:
  replicas: 1
  service:
    type: LoadBalancer  # 외부 접근을 위해 LoadBalancer 사용
  defaultUser:
    enabled: true
    username: airflow
    password: airflow
    email: airflow@org.kr

# Scheduler 설정
scheduler:
  replicas: 1

# Worker 설정
workers:
  replicas: 4

# k8s persistence => docker volume
persistence:
  enabled: true
  existingClaim: ""  # 기존 PVC 사용 시 설정
  storageClass: "standard"
  accessMode: ReadWriteOnce # << params
  # template
  #  """ReadWriteOnce (RWO): PVC를 하나의 노드에서 읽기/쓰기 가능.
  #     ReadOnlyMany (ROX): 여러 노드에서 PVC를 읽기 전용으로 마운트 가능.
  #     ReadWriteMany (RWX): 여러 노드에서 PVC를 읽기/쓰기 가능.
  #  """
  size: 10Gi

# ConfigMap 설정
config:
  AIRFLOW__CORE__EXECUTOR: KubernetesExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgresql/airflow
  AIRFLOW__KUBERNETES__NAMESPACE: airflow_cluster
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: apache/airflow
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "2.5.1"

# 추가 설정 가능