apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-airflow.name" . }}-webserver
  labels:
    {{- include "my-airflow.labels" . | nindent 4 }}
    component: webserver
spec:
  type: {{ .Values.webserver.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "my-airflow.name" . }}
    component: webserver
  ports:
    - port: {{ .Values.webserver.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
