{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-airflow.name" . }}-redis
  labels:
    {{- include "my-airflow.labels" . | nindent 4 }}
    component: redis
spec:
  type: {{ .Values.redis.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "my-airflow.name" . }}
    component: redis
  ports:
    - port: {{ .Values.redis.service.port | default 6379 }}
      targetPort: 6379
      name: redis
{{- end }}
