{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my-airflow.name" . }}-postgres
  labels:
    {{- include "my-airflow.labels" . | nindent 4 }}
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-airflow.name" . }}
      component: postgres
  serviceName: {{ include "my-airflow.name" . }}-postgres
  template:
    metadata:
      labels:
        {{- include "my-airflow.labels" . | nindent 8 }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
{{- end }}
